#  Hi,We are free ,please avoid fraud.
#  Generated at 2023-12-31 00:00 by ClodQiu
#  Clash Meta Core
ipv6: true
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
geo-update-interval: 24
geodata-mode: true
geodata-loader: memconservative

geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  nameserver:
  - "https://dns.cloudflare.com/dns-query#dns"
  - "https://dns.google/dns-query#dns"
  default-nameserver:
  - quic://223.5.5.5:853
  - quic://223.6.6.6:853
  - tls://1.12.12.12:853
  - quic://[2400:3200:baba::1]:853
  proxy-server-nameserver:
  - quic://223.5.5.5:853
  - quic://223.6.6.6:853
  - tls://1.12.12.12:853
  - quic://[2400:3200:baba::1]:853
  nameserver-policy:
    "+.jd.com":
    - udp://223.5.5.5:53
    - udp://223.6.6.6:53
    - udp://219.147.1.66:53
    - udp://[2400:3200:baba::1]:53
    - udp://[240e:4e:800::66]:53
    geosite:category-ads-all: rcode://success
    geosite:cn:
    - udp://223.5.5.5:53
    - udp://223.6.6.6:53
    - udp://219.147.1.66:53
    - udp://[2400:3200:baba::1]:53
    - udp://[240e:4e:800::66]:53
    "+.msftncsi.com":
    - udp://223.5.5.5:53
    - udp://223.6.6.6:53
    - udp://219.147.1.66:53
    - udp://[2400:3200:baba::1]:53
    - udp://[240e:4e:800::66]:53
    "+.msftconnecttest.com":
    - udp://223.5.5.5:53
    - udp://223.6.6.6:53
    - udp://219.147.1.66:53
    - udp://[2400:3200:baba::1]:53
    - udp://[240e:4e:800::66]:53
